#!/bin/bash

# skips most edge-case tests if set to 1
SKIP=${SKIP:-"0"}

# btrsnap-help
echo -e "\n### btrsnap help"
DRY_RUN=1 btrsnap help
if [ "$SKIP" -eq 0 ]; then
    echo -e "\n### btrsnap -h"
    DRY_RUN=1 btrsnap -h
fi

# btrsnap-env
echo -e "\n### btrsnap env"
DRY_RUN=1 btrsnap env

# btrsnap-list
echo -e "\n### btrsnap l -t"
DRY_RUN=1 btrsnap l -t
if [ "$SKIP" -eq 0 ]; then
    # btrsnap-list help
    echo -e "\n### btrsnap l -h"
    DRY_RUN=1 btrsnap l -h
    # btrsnap-list verbose
    echo -e "\n### btrsnap l -v"
    DRY_RUN=1 btrsnap l -v
    # btrsnap-list simple output
    echo -e "\n### btrsnap l -s"
    DRY_RUN=1 btrsnap l -s
    # btrsnap-list hourly output
    echo -e "\n### btrsnap l --mode 1"
    DRY_RUN=1 btrsnap l --mode 1
    # btrsnap-list table output
    echo -e "\n### btrsnap l -t --mode 0"
    DRY_RUN=1 btrsnap l -t --mode 0
fi

# btrsnap-create
if [ "$SKIP" -eq 0 ]; then
    # btrsnap-create help
    echo -e "\n### btrsnap c -h"
    DRY_RUN=1 btrsnap c -h
    # btrsnap-create default
    echo -e "\n### btrsnap create"
    DRY_RUN=1 btrsnap create
    # btrsnap-create custom format
    echo -e "\n### btrsnap c -f %Y%M"
    DRY_RUN=1 btrsnap c -f %Y%M
    # btrsnap-create iso format
    echo -e "\n### btrsnap c -f iso-8601=seconds"
    DRY_RUN=1 btrsnap c -f iso-8601=seconds
    echo -e "\n### btrsnap c -v"
    # btrsnap-create verbose
    DRY_RUN=1 btrsnap c -v
    echo -e "\n### btrsnap c -b /snappies"
    # btrsnap-create basedir (absolute)
    DRY_RUN=1 btrsnap c -b /snappies
    # btrsnap-create basedir (relative)
    echo -e "\n### btrsnap c -b snappies"
    DRY_RUN=1 btrsnap c -b snappies
    # btrsnap-create message
    echo -e "\n### btrsnap c -v -m \"Some special snapshot\" -b /snaps / root"
    DRY_RUN=1 btrsnap c -v -m "Some special snapshot" -b /snaps / root
    # btrsnap-create (absolute)
    echo -e "\n### btrsnap c -v / /snapshots/root"
    DRY_RUN=1 btrsnap c -v / /snapshots/root
    # btrsnap-create non-subvolume
    echo -e "\n### btrsnap c -v /etc etc"
    DRY_RUN=1 btrsnap c -v /etc etc
    # btrsnap-create hourly
    echo -e "\n### btrsnap c -v --mode 1"
    DRY_RUN=1 btrsnap c -v --mode 1
fi

# btrsnap-remove
if [ "$SKIP" -eq 0 ]; then
    # btrsnap-remove (relative)
    echo -e "\n### btrsnap c -f \"current\" / /snapshots/test"
    echo "#### btrsnap rm -f test/current"
    btrsnap c -f "current" / /snapshots/test
    btrsnap rm -f test/current
    # btrsnap-remove (absolute)
    echo -e "\n### btrsnap c -f \"current\" / /snapshots/test"
    echo "#### btrsnap rm -f /snapshots/test/current"
    btrsnap c -f "current" / /snapshots/test
    btrsnap rm -f /snapshots/test/current
    # btrsnap-remove default
    echo -e "\n### btrsnap c -f \"current\" / /snapshots/test"
    echo "#### btrsnap rm -f"
    btrsnap c -f "current" / /snapshots/test
    btrsnap rm -f
    # btrsnap-remove by index
    echo "#### btrsnap rm -f -1"
    btrsnap c -f "current" / /snapshots/test
    btrsnap rm -f -1
    # TODO: btrsnap-remove mode
    # TODO: btrsnap-remove wildcard
fi

# btrsnap-diff
if [ "$SKIP" -eq 0 ]; then
    # btrsnap-diff help
    echo -e "\n### btrsnap d -h"
    DRY_RUN=1 btrsnap d -h
    # btrsnap-diff default
    echo -e "\n### btrsnap d | head -n 30"
    btrsnap l &> /dev/null
    btrsnap d | head -n 30
fi
# btrsnap-diff latest
echo -e "\n###  touch /test_file.txt"
echo "###  btrsnap c -f \"prev\" / test"
echo "###  echo \"TEST CONTENT\" >> /test_file.txt"
echo "#### btrsnap diff /snapshots/test/prev 0"
echo "###  btrsnap rm -f /snapshots/test/prev"
echo "###  rm /test_file.txt"
touch /test_file.txt
btrsnap c -f "prev" / test &>/dev/null
echo "TEST CONTENT" >> /test_file.txt
btrsnap diff /snapshots/test/prev 0
btrsnap rm -f /snapshots/test/prev &>/dev/null
rm /test_file.txt
# btrsnap-diff file
echo -e "\n###  touch /test_file.txt"
echo "###  btrsnap c -f \"prev\" / test"
echo "###  echo \"TEST CONTENT\" >> /test_file.txt"
echo "#### btrsnap d -f /test_file.txt test/prev"
echo "###  btrsnap rm -f /snapshots/test/prev"
echo "###  rm /test_file.txt"
touch /test_file.txt
btrsnap c -f "prev" / test &>/dev/null
echo "TEST CONTENT" >> /test_file.txt
btrsnap d -f /test_file.txt test/prev
btrsnap rm -f /snapshots/test/prev &>/dev/null
rm /test_file.txt

# btrsnap-undo
if [ "$SKIP" -eq 0 ]; then
    # btrsnap-undo help
    echo "### btrsnap undo -h"
    btrsnap undo -h
    # btrsnap-undo (relative)
    echo -e "\n###  touch test_file.txt"
    echo "###  echo \"THIS SHOULD BE THE ONLY LINE AFTER btrsnap-undo\" >> test_file.txt"
    echo "###  btrsnap c -f \"prev\" /home /snapshots/test"
    echo "###  echo \"OHHH, SNAP! THIS IS ANOTHER LINE\" >> test_file.txt"
    echo "#### btrsnap undo test_file.txt /snapshots/test/prev"
    echo "###  cat test_file.txt"
    echo "###  btrsnap rm -f /snapshots/test/prev"
    echo "###  rm test_file.txt"
    touch test_file.txt
    echo "THIS SHOULD BE THE ONLY LINE AFTER btrsnap-undo" >> test_file.txt
    btrsnap c -f "prev" /home /snapshots/test &>/dev/null
    echo "OHHH, SNAP! THIS IS ANOTHER LINE" >> test_file.txt
    btrsnap undo test_file.txt /snapshots/test/prev
    cat test_file.txt
    btrsnap rm -f /snapshots/test/prev &>/dev/null
    rm test_file.txt
    # btrsnap-undo (from non-root)
    echo -e "\n###  touch /home/test_file.txt"
    echo "###  echo \"THIS SHOULD BE THE ONLY LINE AFTER btrsnap-undo\" >> /home/test_file.txt"
    echo "###  btrsnap c -f \"prev\" /home /snapshots/test"
    echo "###  echo \"OHHH, SNAP! THIS IS ANOTHER LINE\" >> /home/test_file.txt"
    echo "#### btrsnap undo /home/test_file.txt /snapshots/test/prev"
    echo "###  cat /home/test_file.txt"
    echo "###  btrsnap rm -f /snapshots/test/prev"
    echo "###  rm /home/test_file.txt"
    touch /home/test_file.txt
    echo "THIS SHOULD BE THE ONLY LINE AFTER btrsnap-undo" >> /home/test_file.txt
    btrsnap c -f "prev" /home /snapshots/test &>/dev/null
    echo "OHHH, SNAP! THIS IS ANOTHER LINE" >> /home/test_file.txt
    btrsnap undo /home/test_file.txt /snapshots/test/prev
    cat /home/test_file.txt
    btrsnap rm -f /snapshots/test/prev &>/dev/null
    rm /home/test_file.txt
    # btrsnap-undo default
    echo -e "\n###  touch /test_file.txt"
    echo "###  echo \"THIS SHOULD BE THE ONLY LINE AFTER btrsnap-undo\" >> /test_file.txt"
    echo "###  btrsnap c -f \"prev\" / /snapshots/test"
    echo "###  echo \"OHHH, SNAP! THIS IS ANOTHER LINE\" >> /test_file.txt"
    echo "#### btrsnap undo /test_file.txt"
    echo "###  cat /test_file.txt"
    echo "###  btrsnap rm -f /snapshots/test/prev"
    echo "###  rm /test_file.txt"
    touch /test_file.txt
    echo "THIS SHOULD BE THE ONLY LINE AFTER btrsnap-undo" >> /test_file.txt
    btrsnap c -f "prev" / /snapshots/test &>/dev/null
    echo "OHHH, SNAP! THIS IS ANOTHER LINE" >> /test_file.txt
    btrsnap undo /test_file.txt
    cat /test_file.txt
    btrsnap rm -f /snapshots/test/prev &>/dev/null
    rm /test_file.txt
    # btrsnap-undo directory
    echo -e "\n###  mkdir /testdir"
    echo "###  touch /testdir/test_file.txt"
    echo "###  echo \"THIS SHOULD BE THE ONLY LINE AFTER btrsnap-undo\" >> /testdir/test_file.txt"
    echo "###  btrsnap c -f \"prev\" / /snapshots/test"
    echo "###  echo \"OHHH, SNAP! THIS IS ANOTHER LINE\" >> /testdir/test_file.txt"
    echo "#### btrsnap undo /testdir"
    echo "###  cat /testdir/test_file.txt"
    echo "###  btrsnap rm -f /snapshots/test/prev"
    echo "###  rm -r /testdir"
    mkdir /testdir
    touch /testdir/test_file.txt
    echo "THIS SHOULD BE THE ONLY LINE AFTER btrsnap-undo" >> /testdir/test_file.txt
    btrsnap c -f "prev" / /snapshots/test &>/dev/null
    echo "OHHH, SNAP! THIS IS ANOTHER LINE" >> /testdir/test_file.txt
    btrsnap undo /testdir
    cat /testdir/test_file.txt
    btrsnap rm -f /snapshots/test/prev &>/dev/null
    rm -r /testdir
fi
# btrsnap undo file
echo -e "\n###  touch /test_file.txt"
echo "###  echo \"THIS SHOULD BE THE ONLY LINE AFTER btrsnap-undo\" >> /test_file.txt"
echo "###  btrsnap c -f \"prev\" / /snapshots/test"
echo "###  echo \"OHHH, SNAP! THIS IS ANOTHER LINE\" >> /test_file.txt"
echo "#### btrsnap undo /test_file.txt /snapshots/test/prev"
echo "###  cat test_file.txt"
echo "###  btrsnap rm -f /snapshots/test/prev"
echo "###  rm /test_file.txt"
touch /test_file.txt
echo "THIS SHOULD BE THE ONLY LINE AFTER btrsnap-undo" >> /test_file.txt
btrsnap c -f "prev" / /snapshots/test &>/dev/null
echo "OHHH, SNAP! THIS IS ANOTHER LINE" >> /test_file.txt
btrsnap undo /test_file.txt /snapshots/test/prev
cat /test_file.txt
btrsnap rm -f /snapshots/test/prev &>/dev/null
rm /test_file.txt


# btrsnap-restore
echo ""
btrfs subvolume create $HOME/btrsnap_test

if [ "$SKIP" -eq 0 ]; then
    # btrsnap-restore help
    btrsnap restore --help
    # btrsnap-restore device 0
    echo -e "\n###  btrsnap c -f \"current\" $HOME/btrsnap_test /snapshots/test"
    echo "###  touch $HOME/btrsnap_test/test_file.txt"
    echo "#### btrsnap restore /snapshots/test/current $HOME/btrsnap_test"
    echo "###  ls $HOME/btrsnap_test/test_file.txt"
    echo "###  btrsnap rm -f /snapshots/test/current"
    btrsnap c -f "current" $HOME/btrsnap_test /snapshots/test &>/dev/null
    touch $HOME/btrsnap_test/test_file.txt
    btrsnap restore -d 0 /snapshots/test/current $HOME/btrsnap_test
    ls $HOME/btrsnap_test/test_file.txt 2> /dev/null
    btrsnap rm -f /snapshots/test/current &>/dev/null
    # btrsnap-restore device 1
    echo -e "\n###  btrsnap c -f \"current\" $HOME/btrsnap_test /snapshots/test"
    echo "###  touch $HOME/btrsnap_test/test_file.txt"
    echo "#### btrsnap restore /snapshots/test/current $HOME/btrsnap_test"
    echo "###  ls $HOME/btrsnap_test/test_file.txt"
    echo "###  btrsnap rm -f /snapshots/test/current"
    btrsnap c -f "current" $HOME/btrsnap_test /snapshots/test &>/dev/null
    touch $HOME/btrsnap_test/test_file.txt
    btrsnap restore -d 1 /snapshots/test/current $HOME/btrsnap_test
    ls $HOME/btrsnap_test/test_file.txt 2> /dev/null
    btrsnap rm -f /snapshots/test/current &>/dev/null
    # btrsnap-restore device 2
    echo -e "\n###  btrsnap c -f \"current\" $HOME/btrsnap_test /snapshots/test"
    echo "###  touch $HOME/btrsnap_test/test_file.txt"
    echo "#### btrsnap restore /snapshots/test/current $HOME/btrsnap_test"
    echo "###  ls $HOME/btrsnap_test/test_file.txt"
    echo "###  btrsnap rm -f /snapshots/test/current"
    btrsnap c -f "current" $HOME/btrsnap_test /snapshots/test &>/dev/null
    touch $HOME/btrsnap_test/test_file.txt
    btrsnap restore -d 2 /snapshots/test/current $HOME/btrsnap_test
    ls $HOME/btrsnap_test/test_file.txt 2> /dev/null
    btrsnap rm -f /snapshots/test/current &>/dev/null
    # btrsnap-restore default
    echo -e "\n###  btrsnap c -f \"current\" $HOME/btrsnap_test /snapshots/test"
    echo "###  touch $HOME/btrsnap_test/test_file.txt"
    echo "#### btrsnap restore -d 1"
    echo "###  ls $HOME/btrsnap_test/test_file.txt"
    echo "###  btrsnap rm -f /snapshots/test/current"
    btrsnap c -f "current" $HOME/btrsnap_test /snapshots/test &>/dev/null
    touch $HOME/btrsnap_test/test_file.txt
    btrsnap restore -d 1
    ls $HOME/btrsnap_test/test_file.txt 2> /dev/null
    btrsnap rm -f /snapshots/test/current &>/dev/null
fi
# btrsnap-restore default subvolume
echo "###  touch $HOME/btrsnap_test/test_file.txt"
echo "###  echo \"THIS SHOULD BE THE ONLY LINE AFTER btrsnap-restore\" >> $HOME/btrsnap_test/test_file.txt"
echo "###  btrsnap c -f \"btrsnap_test\" $HOME/btrsnap_test /snapshots/test"
echo "###  echo \"This content should not be visible after btrsnap-restore\" >> $HOME/btrsnap_test/test_file.txt"
echo "#### btrsnap restore -d 0 /snapshots/test/btrsnap_test"
echo "###  cat $HOME/btrsnap_test/test_file.txt"
echo "###  btrsnap rm -f /snapshots/test/btrsnap_test"
touch $HOME/btrsnap_test/test_file.txt
echo "THIS SHOULD BE THE ONLY LINE AFTER btrsnap-restore" >> $HOME/btrsnap_test/test_file.txt
btrsnap c -f "btrsnap_test" $HOME/btrsnap_test /snapshots/test &>/dev/null
echo "OHHH, SNAP! THIS IS ANOTHER LINE" >> $HOME/btrsnap_test/test_file.txt
btrsnap restore -d 0 /snapshots/test/btrsnap_test
cat $HOME/btrsnap_test/test_file.txt
btrsnap rm -f /snapshots/test/btrsnap_test &>/dev/null
rm $HOME/btrsnap_test/test_file.txt

btrfs subvolume delete $HOME/btrsnap_test
